name = "JuBEMeshes"
uuid = "d6dacf24-aced-4a7c-8f6c-751077a72dc6"
authors = ["Lucas Pacheco"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
